### ISSUE TITLE
unit test is broken

### ISSUE THREAD

**Issue by John-Ragland** [ooipy/ooipy#50]
something breaks in github workflow

`Error: The process '/usr/share/miniconda3/condabin/conda' failed with exit code 1`

**Comment by John-Ragland** [comment]
@lsetiawan Do you know what might be causing this?

**Comment by lsetiawan** [comment]
I notice that your environment file is very specific. It would be good to relax the hard pinning of the environment file, and just pin the ones that you absolutely need, otherwise, conda can get confused when resolving packages.

**Comment by lsetiawan** [comment]
I've made PR #53 to hopefully fix this.
