### ISSUE TITLE
Failed to install calibration file

### ISSUE THREAD

**Issue by FelixSchwock** [ooipy/ooipy#51]
When I install ooipy from my local computer or from github it doesn't install the "calibration_by_assetID.pkl" containing the calibration data for the LF and BB hydrophones. I get the following error message when calling for example compute_welch_psd: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fschwock\\AppData\\Local\\Continuum\\anaconda3\\envs\\obspy\\lib\\site-packages\\ooipy/hydrophone/calibration_by_assetID.pkl'

I don't know if this is/will be an issue when installing ooipy from PyPI.

**Comment by John-Ragland** [comment]
I'm going to look into if that can be implemented with a csv. (might not fix the issue, but it will be cleaner)
