### ISSUE TITLE
Outdated demo notebook for request module

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#70]
There is a link to "[notebook](https://ooipy.readthedocs.io/en/latest/_static/test_request.html)" on the Request Module [page](https://ooipy.readthedocs.io/en/latest/request.html) of docs, it is outdated. Should be recreated with current version of OOIPy or just removed.

![image](https://user-images.githubusercontent.com/12860284/125480624-43dacda2-43b1-4d3c-a75f-b2fcc297d6bd.png)
![image](https://user-images.githubusercontent.com/12860284/125480689-70fa8034-d832-4796-9bd4-14138a6e67c2.png)

**Comment by John-Ragland** [comment]
Thanks for pointing this out. I've made a PR with these changes. They changes should show up in the next release which should be coming soon. In the mean time, the demo ooipy/ooipy_demo.ipynb gives a general overview of hydrophone data usage and should be up to date.

**Comment by Molkree** [comment]
Closing as this was resolved in #71
