### ISSUE TITLE
Question: flake8 Action relevance

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#72]
Just a question, why do you keep [flake8 workflow](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.github/workflows/flake8.yml) around if flake8 is also being checked in [linting workflow](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.github/workflows/linting.yml) through ([deprecated](https://github.com/pre-commit/action#:~:text=DEPRECATED%20this%20action%20is%20in%20maintenance-only%20mode%20and%20will%20not%20be%20accepting%20new%20features.)) pre-commit Action?

**Comment by FelixSchwock** [comment]
We created the flake8 workflow first and later @lsetiawan set up the linting. Don, do you agree with @Molkree that we can remove the flake8 workflow?

**Comment by lsetiawan** [comment]
I agree. Let's remove the flake8 workflow.
