### ISSUE TITLE
Consider using pre-commit.ci

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#73]
As title says, it will keep your [pre-commit config](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.pre-commit-config.yaml) up to date and will lint incoming PRs automatically (and fix if tools apply fixes).
For example right now all 4 tools in pre-commit config have outdated versions specified.
[pre-commit.ci](https://pre-commit.ci/)

**Comment by FelixSchwock** [comment]
Thank you for suggesting it. That sounds like a great tool. We will add it to the project

**Comment by lsetiawan** [comment]
I just set it up. Thanks for the suggestion @Molkree
