### ISSUE TITLE
No Black config in repository

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#74]
I see that you allowed [100 chars line length](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.pre-commit-config.yaml#L17) in pre-commit config for Black, however there's no config for Black in the repository itself.
This will not introduce new warnings but it will make Black too eager to wrap lines (because the default is 88 char length) which is undesirable (I assume 100 char length was an informed decision).
I propose to add a simple pyproject.toml config for Black and remove specifying line length in pre-commit config.
I can send PR if needed.

**Comment by FelixSchwock** [comment]
That sounds great. If you could make a PR, we would really appreciate it as we are not really experienced with the continuous integration stuff.

**Comment by Molkree** [comment]
Sure, do you want PRs sent to the `development` or `master` branch?
