### ISSUE TITLE
Output log from unit tests gets overwritten

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#76]
You run two parallel jobs, one for Python 3.7 and one for Python 3.8. The last step of the job is log uploading but because this step is the same in both jobs, the longest job just overwrites the output artifact. Artifact name should contain a Python version to alleviate this issue.

**Comment by FelixSchwock** [comment]
Ah thanks for the note. If you know where this can be fixed in the workflow files, would you mind sending a PR? Otherwise we can probably figure that out as well.
