### ISSUE TITLE
Question: What Python versions are supported?

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#77]
On PyPI it says you support [Python >=3.6](https://pypi.org/project/ooipy/#:~:text=Requires%3A-,Python%20%3E%3D3.6,-Maintainers) however in unit test workflow I only see [3.7 and 3.8](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.github/workflows/unit_test.yml#L12).
What about 3.6? 3.9 (we've been using OOIPy with it for [some time](https://github.com/orcasound/orca-action-workflow/actions/workflows/ooi_processing.yml), though not in conda)? (Maybe even 3.10 haha?)

**Comment by FelixSchwock** [comment]
I am pretty certain that OOIPy should work will all python version >=3.6 (it might even work with older versions). That we run the unit tests only on 3.7 and 3.8 can probably be attributed to our laziness. Do you know a way for the unit tests to be run on all python versions at and above a specified version? So that we only have to specify the lowest version (lets say 3.6) in the [unit_test.yml](https://github.com/ooipy/ooipy/blob/master/.github/workflows/unit_test.yml)  and it runs the unit tests automatically for 3.6, 3.7, 3.8, ...

**Comment by Molkree** [comment]
No, I don't think it's possible, you have to specify the version. It's not too much work really, Python releases only once a year!
But covering all versions might be tricky for another reason: you test on conda. You only have conda environment files for 3.7 and 3.8 so other versions simply won't have the corresponding file. Now to the question of why you even have different files for each version, the only difference between them is the Python version.

Testing without conda would be faster but if you want to test that everything works in conda then you'd need to create environment files for each Python version (3.6 and 3.9, 3.10 is not on conda yet).

I would suggest removing Python dependency from conda environment file and keeping only one file instead. Then testing will be possible using just one env file + specifying Python version in workflow (you already [do it](https://github.com/ooipy/ooipy/blob/536b144eecd38c9eabcb7aa2e5db834e6e13f465/.github/workflows/unit_test.yml#L35) honestly).

**Comment by lsetiawan** [comment]
> I would suggest removing Python dependency from conda environment file and keeping only one file instead. Then testing will be possible using just one env file + specifying Python version in workflow (you already do it honestly).

We would like to have conda support as the scientific community often times uses conda. I think it's fine to keep the multiple conda files. The general best practice is always better to be **explicit** rather than implicit.

**Comment by Molkree** [comment]
Alright, got it, so I guess you'd want 2 files added then, to test on Python 3.6 and 3.9?

**Comment by lsetiawan** [comment]
That would be great! 😄 Thanks!

**Comment by Molkree** [comment]
Closing as the question was answered and PR testing on all supported versions was merged.
